-- ============================================================
-- InsightPilot AI
-- V1 — Data Assistant Foundation
-- PostgreSQL Core Business Schema
-- ============================================================

-- ============================================================
-- 1. REGIONS
-- ============================================================

CREATE TABLE regions (
    region_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_code VARCHAR(10) NOT NULL UNIQUE,
    region_name VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 2. CUSTOMERS
-- ============================================================

CREATE TABLE customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_code VARCHAR(20) NOT NULL UNIQUE,
    customer_name VARCHAR(120) NOT NULL,
    region_id BIGINT NOT NULL,
    signup_date DATE NOT NULL,
    account_status VARCHAR(20) NOT NULL
        CHECK (
            account_status IN (
                'ACTIVE',
                'INACTIVE',
                'SUSPENDED',
                'CLOSED'
            )
        ),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_customer_region
        FOREIGN KEY (region_id)
        REFERENCES regions(region_id)
);

-- ============================================================
-- 3. SUBSCRIPTIONS
-- ============================================================

CREATE TABLE subscriptions (
    subscription_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,

    plan_name VARCHAR(30) NOT NULL
        CHECK (
            plan_name IN (
                'FREE',
                'BASIC',
                'PRO',
                'ENTERPRISE'
            )
        ),

    subscription_status VARCHAR(20) NOT NULL
        CHECK (
            subscription_status IN (
                'ACTIVE',
                'CANCELLED',
                'EXPIRED',
                'PAST_DUE'
            )
        ),

    start_date DATE NOT NULL,
    end_date DATE,

    monthly_price NUMERIC(12,2) NOT NULL
        CHECK (monthly_price >= 0),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_subscription_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id),

    CONSTRAINT chk_subscription_dates
        CHECK (
            end_date IS NULL
            OR end_date >= start_date
        )
);

-- ============================================================
-- 4. PAYMENTS
-- ============================================================

CREATE TABLE payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    subscription_id BIGINT,

    amount NUMERIC(12,2) NOT NULL
        CHECK (amount >= 0),

    payment_status VARCHAR(20) NOT NULL
        CHECK (
            payment_status IN (
                'SUCCESS',
                'FAILED',
                'PENDING'
            )
        ),

    payment_date TIMESTAMP NOT NULL,

    payment_method VARCHAR(30) NOT NULL
        CHECK (
            payment_method IN (
                'CARD',
                'UPI',
                'NET_BANKING',
                'WALLET'
            )
        ),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payment_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id),

    CONSTRAINT fk_payment_subscription
        FOREIGN KEY (subscription_id)
        REFERENCES subscriptions(subscription_id)
);

-- ============================================================
-- 5. REFUNDS
-- ============================================================

CREATE TABLE refunds (
    refund_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,

    refund_amount NUMERIC(12,2) NOT NULL
        CHECK (refund_amount > 0),

    refund_reason VARCHAR(100) NOT NULL,
    refund_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_refund_payment
        FOREIGN KEY (payment_id)
        REFERENCES payments(payment_id),

    CONSTRAINT fk_refund_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id)
);

-- ============================================================
-- 6. PRODUCTS
-- ============================================================

CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code VARCHAR(20) NOT NULL UNIQUE,
    product_name VARCHAR(120) NOT NULL,
    category VARCHAR(50) NOT NULL,

    unit_price NUMERIC(12,2) NOT NULL
        CHECK (unit_price >= 0),

    product_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
        CHECK (
            product_status IN (
                'ACTIVE',
                'INACTIVE'
            )
        ),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ============================================================
-- 7. ORDERS
-- ============================================================

CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,

    quantity INTEGER NOT NULL
        CHECK (quantity > 0),

    order_amount NUMERIC(12,2) NOT NULL
        CHECK (order_amount >= 0),

    order_status VARCHAR(20) NOT NULL
        CHECK (
            order_status IN (
                'COMPLETED',
                'CANCELLED',
                'PENDING',
                'REFUNDED'
            )
        ),

    order_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_order_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id),

    CONSTRAINT fk_order_product
        FOREIGN KEY (product_id)
        REFERENCES products(product_id)
);

-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_customers_region
    ON customers(region_id);

CREATE INDEX idx_customers_status
    ON customers(account_status);

CREATE INDEX idx_subscriptions_customer
    ON subscriptions(customer_id);

CREATE INDEX idx_subscriptions_status
    ON subscriptions(subscription_status);

CREATE INDEX idx_subscriptions_plan
    ON subscriptions(plan_name);

CREATE INDEX idx_payments_customer
    ON payments(customer_id);

CREATE INDEX idx_payments_status
    ON payments(payment_status);

CREATE INDEX idx_payments_date
    ON payments(payment_date);

CREATE INDEX idx_refunds_customer
    ON refunds(customer_id);

CREATE INDEX idx_refunds_date
    ON refunds(refund_date);

CREATE INDEX idx_orders_customer
    ON orders(customer_id);

CREATE INDEX idx_orders_product
    ON orders(product_id);

CREATE INDEX idx_orders_date
    ON orders(order_date);
